runtime: go125

instance_class: F2

automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.65

env_variables:
  ENV: "production"
  DB_HOST: "34.101.167.164"
  DB_PORT: "3306"
  DB_NAME: "wisata_db"
  DB_USER: "yoda"
